import {
  Grid,
  H1,
  H2,
  Pill,
  Row,
  Select,
  Spacer,
  Stack,
  Stat,
  Table,
  Text,
  TextInput,
  useCanvasState,
  useHostTheme,
} from "cursor/canvas";

// Generated by: python daily_summary/generate_daily_elite_summary.py
// Template reference — live canvas: ~/.cursor/projects/<workspace>/canvases/elite-daily-summary-YYYY-MM-DD.canvas.tsx

const REPORT = {
  date: "YYYY-MM-DD",
  weekday: "Weekday",
  priorDate: "YYYY-MM-DD",
  overallRevenue: "$0",
  eliteSharePct: "0.0%",
  revenueThis: "$0",
  revenuePrior: "$0",
  revenueChange: "$0",
  revenuePct: "0.0%",
  playersThis: 0,
  playersPrior: 0,
  playersChange: 0,
  playersPct: "0.0%",
  overallPlayersThis: 0,
  overallPlayersChange: 0,
  overallPlayersPct: "0.0%",
};

type PlayerRow = {
  aid: string;
  name: string;
  agent: string;
  thisDay: string;
  priorDay: string;
  delta: string;
  deposits7d: string;
  holdPct7d: string;
  bets7d: string;
  ggr7d: string;
  ngr7d: string;
  spins7d: string;
  reason: string;
  reasonDetail: string;
  action: string;
  tone?: "success" | "danger" | "warning" | "info" | "neutral";
};

const TOP10: PlayerRow[] = [];

const AGENTS: string[] = [];
const REASONS = Array.from(new Set(TOP10.map((p) => p.reason))).sort();

function matchesSearch(row: PlayerRow, query: string): boolean {
  if (!query.trim()) return true;
  const q = query.trim().toLowerCase();
  return (
    row.name.toLowerCase().includes(q) ||
    row.aid.includes(q) ||
    row.agent.toLowerCase().includes(q) ||
    row.reason.toLowerCase().includes(q) ||
    row.reasonDetail.toLowerCase().includes(q) ||
    row.action.toLowerCase().includes(q)
  );
}

export default function EliteDailySummary() {
  const theme = useHostTheme();
  const [search, setSearch] = useCanvasState("search", "");
  const [agent, setAgent] = useCanvasState("agent", "all");
  const [reason, setReason] = useCanvasState("reason", "all");

  const filtered = TOP10.filter((row) => {
    if (agent !== "all" && row.agent !== agent) return false;
    if (reason !== "all" && row.reason !== reason) return false;
    return matchesSearch(row, search);
  });

  const filterActive = search.trim() !== "" || agent !== "all" || reason !== "all";
  const dayShort = REPORT.weekday.slice(0, 3);

  return (
    <Stack gap={16} style={{ padding: 20, maxWidth: 1080, background: theme.bg.editor }}>
      <Stack gap={4}>
        <H1>Elite Daily Decline Dashboard</H1>
        <Text tone="tertiary" size="small">
          {REPORT.weekday} {REPORT.date} vs prior {REPORT.weekday} {REPORT.priorDate}
        </Text>
        <Text tone="quaternary" size="small">
          Source: BigQuery silver-social-games-data
        </Text>
      </Stack>

      <Grid columns={4} gap={12}>
        <Stat label="Platform revenue" value={REPORT.overallRevenue} tone="neutral" />
        <Stat label={`Elite revenue, this ${REPORT.weekday}`} value={REPORT.revenueThis} tone="info" />
        <Stat label="Elite share of platform" value={REPORT.eliteSharePct} tone="neutral" />
        <Stat
          label="Elite WoW change"
          value={`${REPORT.revenueChange} (${REPORT.revenuePct})`}
          tone="danger"
        />
      </Grid>
      <Grid columns={2} gap={12}>
        <Stat
          label={`Platform purchased players, this ${REPORT.weekday}`}
          value={`${REPORT.overallPlayersThis} (${REPORT.overallPlayersChange >= 0 ? "+" : ""}${REPORT.overallPlayersChange}, ${REPORT.overallPlayersPct})`}
          tone="warning"
        />
        <Stat
          label={`Elite purchased players, this ${REPORT.weekday}`}
          value={`${REPORT.playersThis} (${REPORT.playersChange >= 0 ? "+" : ""}${REPORT.playersChange}, ${REPORT.playersPct})`}
          tone="warning"
        />
      </Grid>

      <Stack gap={8}>
        <Row gap={8} align="center" wrap>
          <H2>Top 10 Same Day Comparison</H2>
          <Spacer />
          <Text tone="tertiary" size="small">
            {filterActive ? `Showing ${filtered.length} of ${TOP10.length}` : `${TOP10.length} players`}
          </Text>
        </Row>

        <Row gap={8} align="center" wrap>
          <TextInput
            value={search}
            onChange={setSearch}
            placeholder="Search name, AID, agent, reason…"
            type="search"
            style={{ flex: "1 1 220px", minWidth: 200 }}
          />
          <Select
            value={agent}
            onChange={setAgent}
            options={[
              { value: "all", label: "All agents" },
              ...AGENTS.map((a) => ({ value: a, label: a })),
            ]}
            style={{ flex: "0 0 140px" }}
          />
        </Row>

        <Row gap={6} wrap>
          <Pill active={reason === "all"} onClick={() => setReason("all")} size="sm">
            All reasons
          </Pill>
          {REASONS.map((r) => (
            <Pill key={r} active={reason === r} onClick={() => setReason(r)} size="sm">
              {r}
            </Pill>
          ))}
        </Row>

        <Table
          headers={["#", "Agent", "AID", "Name", `This ${dayShort}`, `Prior ${dayShort}`, "Delta", "7d Deposits", "7d Hold %", "7d Bets", "7d GGR", "7d NGR", "7d Spins", "Reason", "Action"]}
          rows={filtered.map((p, i) => [
            String(i + 1),
            p.agent,
            p.aid,
            p.name,
            p.thisDay,
            p.priorDay,
            p.delta,
            p.deposits7d,
            p.holdPct7d,
            p.bets7d,
            p.ggr7d,
            p.ngr7d,
            p.spins7d,
            p.reasonDetail,
            p.action,
          ])}
          columnAlign={["center", "left", "left", "left", "right", "right", "right", "right", "right", "right", "right", "right", "right", "left", "left"]}
          rowTone={filtered.map((p) => p.tone)}
          striped
          stickyHeader
          emptyMessage="No players match the current filters."
        />
      </Stack>

      <Text tone="quaternary" size="small">
        Handoffs: @wow-drop-reason-analysis · decline protocol: generate_decline_protocol.py
      </Text>
    </Stack>
  );
}
